# WHEEL_RADIUS = 0.030
# WHEEL_SEPARATION = 0.24
# VEL_TO_PWM = 278
# PULSES_PER_REVOLUTION = 138
# PULSES_PER_METER = 732

# Controller manager configuration
controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    ### Controllers to be initialized at startup ###
    diff_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_controller:
  ros__parameters:
    publish_rate: 50.0
    left_wheel_names: ['joint_wheel_left']
    right_wheel_names: ['joint_wheel_right']
    wheels_per_side: 1
    wheel_separation: 0.24
    wheel_radius: 0.03
    base_frame_id: base_link
    use_stamped_vel: false

    linear.x.has_velocity_limits: false
    linear.x.has_acceleration_limits: false
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 0.0
    linear.x.min_velocity: 0.0
    linear.x.max_acceleration: 0.0
    linear.x.min_acceleration: 0.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: false
    angular.z.has_acceleration_limits: false
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 0.0
    angular.z.min_velocity: 0.0
    angular.z.max_acceleration: 0.0
    angular.z.min_acceleration: 0.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0